/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SuppliesRequestRouteImport } from './routes/supplies-request'
import { Route as SuppliesRouteImport } from './routes/supplies'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as QcRouteImport } from './routes/qc'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as ExpenseScanRouteImport } from './routes/expense-scan'
import { Route as ExpenseMineRouteImport } from './routes/expense-mine'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSuppliesReportsRouteImport } from './routes/_protected.supplies-reports'
import { Route as ProtectedSuppliesDashboardRouteImport } from './routes/_protected.supplies-dashboard'
import { Route as ProtectedSuppliesAdminRouteImport } from './routes/_protected.supplies-admin'
import { Route as ProtectedStorageRouteImport } from './routes/_protected.storage'
import { Route as ProtectedQcSummaryRouteImport } from './routes/_protected.qc-summary'
import { Route as ProtectedQcReportsRouteImport } from './routes/_protected.qc-reports'
import { Route as ProtectedProductionStandardsRouteImport } from './routes/_protected.production-standards'
import { Route as ProtectedProductionSetupRouteImport } from './routes/_protected.production-setup'
import { Route as ProtectedProductionExcelRouteImport } from './routes/_protected.production-excel'
import { Route as ProtectedProductionDashboardRouteImport } from './routes/_protected.production-dashboard'
import { Route as ProtectedPackingSummaryRouteImport } from './routes/_protected.packing-summary'
import { Route as ProtectedPackingReportsRouteImport } from './routes/_protected.packing-reports'
import { Route as ProtectedManagePoliciesRouteImport } from './routes/_protected.manage-policies'
import { Route as ProtectedManageRouteImport } from './routes/_protected.manage'
import { Route as ProtectedMaintenanceMasterRouteImport } from './routes/_protected.maintenance-master'
import { Route as ProtectedMaintenanceAdminRouteImport } from './routes/_protected.maintenance-admin'
import { Route as ProtectedLogsUpdateRouteImport } from './routes/_protected.logs-update'
import { Route as ProtectedLogsRouteImport } from './routes/_protected.logs'
import { Route as ProtectedJobLookupRouteImport } from './routes/_protected.job-lookup'
import { Route as ProtectedExpensesReportsRouteImport } from './routes/_protected.expenses-reports'
import { Route as ProtectedExpensesDashboardRouteImport } from './routes/_protected.expenses-dashboard'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedControlRouteImport } from './routes/_protected.control'
import { Route as ProtectedAdminPolicyRouteImport } from './routes/_protected.admin-policy'
import { Route as ProtectedEmployeeProfileIdRouteImport } from './routes/_protected.employee-profile.$id'
import { Route as ApiPublicHooksLineDailySendRouteImport } from './routes/api/public/hooks/line-daily-send'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRequestRoute = SuppliesRequestRouteImport.update({
  id: '/supplies-request',
  path: '/supplies-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesRoute = SuppliesRouteImport.update({
  id: '/supplies',
  path: '/supplies',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseScanRoute = ExpenseScanRouteImport.update({
  id: '/expense-scan',
  path: '/expense-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpenseMineRoute = ExpenseMineRouteImport.update({
  id: '/expense-mine',
  path: '/expense-mine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSuppliesReportsRoute =
  ProtectedSuppliesReportsRouteImport.update({
    id: '/supplies-reports',
    path: '/supplies-reports',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSuppliesDashboardRoute =
  ProtectedSuppliesDashboardRouteImport.update({
    id: '/supplies-dashboard',
    path: '/supplies-dashboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSuppliesAdminRoute = ProtectedSuppliesAdminRouteImport.update({
  id: '/supplies-admin',
  path: '/supplies-admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedStorageRoute = ProtectedStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQcSummaryRoute = ProtectedQcSummaryRouteImport.update({
  id: '/qc-summary',
  path: '/qc-summary',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedQcReportsRoute = ProtectedQcReportsRouteImport.update({
  id: '/qc-reports',
  path: '/qc-reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProductionStandardsRoute =
  ProtectedProductionStandardsRouteImport.update({
    id: '/production-standards',
    path: '/production-standards',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProductionSetupRoute =
  ProtectedProductionSetupRouteImport.update({
    id: '/production-setup',
    path: '/production-setup',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProductionExcelRoute =
  ProtectedProductionExcelRouteImport.update({
    id: '/production-excel',
    path: '/production-excel',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedProductionDashboardRoute =
  ProtectedProductionDashboardRouteImport.update({
    id: '/production-dashboard',
    path: '/production-dashboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPackingSummaryRoute = ProtectedPackingSummaryRouteImport.update({
  id: '/packing-summary',
  path: '/packing-summary',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPackingReportsRoute = ProtectedPackingReportsRouteImport.update({
  id: '/packing-reports',
  path: '/packing-reports',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedManagePoliciesRoute = ProtectedManagePoliciesRouteImport.update({
  id: '/manage-policies',
  path: '/manage-policies',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedManageRoute = ProtectedManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMaintenanceMasterRoute =
  ProtectedMaintenanceMasterRouteImport.update({
    id: '/maintenance-master',
    path: '/maintenance-master',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMaintenanceAdminRoute =
  ProtectedMaintenanceAdminRouteImport.update({
    id: '/maintenance-admin',
    path: '/maintenance-admin',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLogsUpdateRoute = ProtectedLogsUpdateRouteImport.update({
  id: '/logs-update',
  path: '/logs-update',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedLogsRoute = ProtectedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJobLookupRoute = ProtectedJobLookupRouteImport.update({
  id: '/job-lookup',
  path: '/job-lookup',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExpensesReportsRoute =
  ProtectedExpensesReportsRouteImport.update({
    id: '/expenses-reports',
    path: '/expenses-reports',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedExpensesDashboardRoute =
  ProtectedExpensesDashboardRouteImport.update({
    id: '/expenses-dashboard',
    path: '/expenses-dashboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedControlRoute = ProtectedControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminPolicyRoute = ProtectedAdminPolicyRouteImport.update({
  id: '/admin-policy',
  path: '/admin-policy',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEmployeeProfileIdRoute =
  ProtectedEmployeeProfileIdRouteImport.update({
    id: '/employee-profile/$id',
    path: '/employee-profile/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiPublicHooksLineDailySendRoute =
  ApiPublicHooksLineDailySendRouteImport.update({
    id: '/api/public/hooks/line-daily-send',
    path: '/api/public/hooks/line-daily-send',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/expense-mine': typeof ExpenseMineRoute
  '/expense-scan': typeof ExpenseScanRoute
  '/maintenance': typeof MaintenanceRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplies': typeof SuppliesRoute
  '/supplies-request': typeof SuppliesRequestRoute
  '/terms': typeof TermsRoute
  '/admin-policy': typeof ProtectedAdminPolicyRoute
  '/control': typeof ProtectedControlRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/expenses-dashboard': typeof ProtectedExpensesDashboardRoute
  '/expenses-reports': typeof ProtectedExpensesReportsRoute
  '/job-lookup': typeof ProtectedJobLookupRoute
  '/logs': typeof ProtectedLogsRoute
  '/logs-update': typeof ProtectedLogsUpdateRoute
  '/maintenance-admin': typeof ProtectedMaintenanceAdminRoute
  '/maintenance-master': typeof ProtectedMaintenanceMasterRoute
  '/manage': typeof ProtectedManageRoute
  '/manage-policies': typeof ProtectedManagePoliciesRoute
  '/packing-reports': typeof ProtectedPackingReportsRoute
  '/packing-summary': typeof ProtectedPackingSummaryRoute
  '/production-dashboard': typeof ProtectedProductionDashboardRoute
  '/production-excel': typeof ProtectedProductionExcelRoute
  '/production-setup': typeof ProtectedProductionSetupRoute
  '/production-standards': typeof ProtectedProductionStandardsRoute
  '/qc-reports': typeof ProtectedQcReportsRoute
  '/qc-summary': typeof ProtectedQcSummaryRoute
  '/storage': typeof ProtectedStorageRoute
  '/supplies-admin': typeof ProtectedSuppliesAdminRoute
  '/supplies-dashboard': typeof ProtectedSuppliesDashboardRoute
  '/supplies-reports': typeof ProtectedSuppliesReportsRoute
  '/employee-profile/$id': typeof ProtectedEmployeeProfileIdRoute
  '/api/public/hooks/line-daily-send': typeof ApiPublicHooksLineDailySendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/expense-mine': typeof ExpenseMineRoute
  '/expense-scan': typeof ExpenseScanRoute
  '/maintenance': typeof MaintenanceRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplies': typeof SuppliesRoute
  '/supplies-request': typeof SuppliesRequestRoute
  '/terms': typeof TermsRoute
  '/admin-policy': typeof ProtectedAdminPolicyRoute
  '/control': typeof ProtectedControlRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/expenses-dashboard': typeof ProtectedExpensesDashboardRoute
  '/expenses-reports': typeof ProtectedExpensesReportsRoute
  '/job-lookup': typeof ProtectedJobLookupRoute
  '/logs': typeof ProtectedLogsRoute
  '/logs-update': typeof ProtectedLogsUpdateRoute
  '/maintenance-admin': typeof ProtectedMaintenanceAdminRoute
  '/maintenance-master': typeof ProtectedMaintenanceMasterRoute
  '/manage': typeof ProtectedManageRoute
  '/manage-policies': typeof ProtectedManagePoliciesRoute
  '/packing-reports': typeof ProtectedPackingReportsRoute
  '/packing-summary': typeof ProtectedPackingSummaryRoute
  '/production-dashboard': typeof ProtectedProductionDashboardRoute
  '/production-excel': typeof ProtectedProductionExcelRoute
  '/production-setup': typeof ProtectedProductionSetupRoute
  '/production-standards': typeof ProtectedProductionStandardsRoute
  '/qc-reports': typeof ProtectedQcReportsRoute
  '/qc-summary': typeof ProtectedQcSummaryRoute
  '/storage': typeof ProtectedStorageRoute
  '/supplies-admin': typeof ProtectedSuppliesAdminRoute
  '/supplies-dashboard': typeof ProtectedSuppliesDashboardRoute
  '/supplies-reports': typeof ProtectedSuppliesReportsRoute
  '/employee-profile/$id': typeof ProtectedEmployeeProfileIdRoute
  '/api/public/hooks/line-daily-send': typeof ApiPublicHooksLineDailySendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/admin': typeof AdminRoute
  '/expense-mine': typeof ExpenseMineRoute
  '/expense-scan': typeof ExpenseScanRoute
  '/maintenance': typeof MaintenanceRoute
  '/packing': typeof PackingRoute
  '/qc': typeof QcRoute
  '/scan': typeof ScanRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplies': typeof SuppliesRoute
  '/supplies-request': typeof SuppliesRequestRoute
  '/terms': typeof TermsRoute
  '/_protected/admin-policy': typeof ProtectedAdminPolicyRoute
  '/_protected/control': typeof ProtectedControlRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/expenses-dashboard': typeof ProtectedExpensesDashboardRoute
  '/_protected/expenses-reports': typeof ProtectedExpensesReportsRoute
  '/_protected/job-lookup': typeof ProtectedJobLookupRoute
  '/_protected/logs': typeof ProtectedLogsRoute
  '/_protected/logs-update': typeof ProtectedLogsUpdateRoute
  '/_protected/maintenance-admin': typeof ProtectedMaintenanceAdminRoute
  '/_protected/maintenance-master': typeof ProtectedMaintenanceMasterRoute
  '/_protected/manage': typeof ProtectedManageRoute
  '/_protected/manage-policies': typeof ProtectedManagePoliciesRoute
  '/_protected/packing-reports': typeof ProtectedPackingReportsRoute
  '/_protected/packing-summary': typeof ProtectedPackingSummaryRoute
  '/_protected/production-dashboard': typeof ProtectedProductionDashboardRoute
  '/_protected/production-excel': typeof ProtectedProductionExcelRoute
  '/_protected/production-setup': typeof ProtectedProductionSetupRoute
  '/_protected/production-standards': typeof ProtectedProductionStandardsRoute
  '/_protected/qc-reports': typeof ProtectedQcReportsRoute
  '/_protected/qc-summary': typeof ProtectedQcSummaryRoute
  '/_protected/storage': typeof ProtectedStorageRoute
  '/_protected/supplies-admin': typeof ProtectedSuppliesAdminRoute
  '/_protected/supplies-dashboard': typeof ProtectedSuppliesDashboardRoute
  '/_protected/supplies-reports': typeof ProtectedSuppliesReportsRoute
  '/_protected/employee-profile/$id': typeof ProtectedEmployeeProfileIdRoute
  '/api/public/hooks/line-daily-send': typeof ApiPublicHooksLineDailySendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/expense-mine'
    | '/expense-scan'
    | '/maintenance'
    | '/packing'
    | '/qc'
    | '/scan'
    | '/sitemap.xml'
    | '/supplies'
    | '/supplies-request'
    | '/terms'
    | '/admin-policy'
    | '/control'
    | '/dashboard'
    | '/expenses-dashboard'
    | '/expenses-reports'
    | '/job-lookup'
    | '/logs'
    | '/logs-update'
    | '/maintenance-admin'
    | '/maintenance-master'
    | '/manage'
    | '/manage-policies'
    | '/packing-reports'
    | '/packing-summary'
    | '/production-dashboard'
    | '/production-excel'
    | '/production-setup'
    | '/production-standards'
    | '/qc-reports'
    | '/qc-summary'
    | '/storage'
    | '/supplies-admin'
    | '/supplies-dashboard'
    | '/supplies-reports'
    | '/employee-profile/$id'
    | '/api/public/hooks/line-daily-send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/expense-mine'
    | '/expense-scan'
    | '/maintenance'
    | '/packing'
    | '/qc'
    | '/scan'
    | '/sitemap.xml'
    | '/supplies'
    | '/supplies-request'
    | '/terms'
    | '/admin-policy'
    | '/control'
    | '/dashboard'
    | '/expenses-dashboard'
    | '/expenses-reports'
    | '/job-lookup'
    | '/logs'
    | '/logs-update'
    | '/maintenance-admin'
    | '/maintenance-master'
    | '/manage'
    | '/manage-policies'
    | '/packing-reports'
    | '/packing-summary'
    | '/production-dashboard'
    | '/production-excel'
    | '/production-setup'
    | '/production-standards'
    | '/qc-reports'
    | '/qc-summary'
    | '/storage'
    | '/supplies-admin'
    | '/supplies-dashboard'
    | '/supplies-reports'
    | '/employee-profile/$id'
    | '/api/public/hooks/line-daily-send'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/admin'
    | '/expense-mine'
    | '/expense-scan'
    | '/maintenance'
    | '/packing'
    | '/qc'
    | '/scan'
    | '/sitemap.xml'
    | '/supplies'
    | '/supplies-request'
    | '/terms'
    | '/_protected/admin-policy'
    | '/_protected/control'
    | '/_protected/dashboard'
    | '/_protected/expenses-dashboard'
    | '/_protected/expenses-reports'
    | '/_protected/job-lookup'
    | '/_protected/logs'
    | '/_protected/logs-update'
    | '/_protected/maintenance-admin'
    | '/_protected/maintenance-master'
    | '/_protected/manage'
    | '/_protected/manage-policies'
    | '/_protected/packing-reports'
    | '/_protected/packing-summary'
    | '/_protected/production-dashboard'
    | '/_protected/production-excel'
    | '/_protected/production-setup'
    | '/_protected/production-standards'
    | '/_protected/qc-reports'
    | '/_protected/qc-summary'
    | '/_protected/storage'
    | '/_protected/supplies-admin'
    | '/_protected/supplies-dashboard'
    | '/_protected/supplies-reports'
    | '/_protected/employee-profile/$id'
    | '/api/public/hooks/line-daily-send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  AdminRoute: typeof AdminRoute
  ExpenseMineRoute: typeof ExpenseMineRoute
  ExpenseScanRoute: typeof ExpenseScanRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PackingRoute: typeof PackingRoute
  QcRoute: typeof QcRoute
  ScanRoute: typeof ScanRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuppliesRoute: typeof SuppliesRoute
  SuppliesRequestRoute: typeof SuppliesRequestRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksLineDailySendRoute: typeof ApiPublicHooksLineDailySendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies-request': {
      id: '/supplies-request'
      path: '/supplies-request'
      fullPath: '/supplies-request'
      preLoaderRoute: typeof SuppliesRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies': {
      id: '/supplies'
      path: '/supplies'
      fullPath: '/supplies'
      preLoaderRoute: typeof SuppliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense-scan': {
      id: '/expense-scan'
      path: '/expense-scan'
      fullPath: '/expense-scan'
      preLoaderRoute: typeof ExpenseScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expense-mine': {
      id: '/expense-mine'
      path: '/expense-mine'
      fullPath: '/expense-mine'
      preLoaderRoute: typeof ExpenseMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/supplies-reports': {
      id: '/_protected/supplies-reports'
      path: '/supplies-reports'
      fullPath: '/supplies-reports'
      preLoaderRoute: typeof ProtectedSuppliesReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/supplies-dashboard': {
      id: '/_protected/supplies-dashboard'
      path: '/supplies-dashboard'
      fullPath: '/supplies-dashboard'
      preLoaderRoute: typeof ProtectedSuppliesDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/supplies-admin': {
      id: '/_protected/supplies-admin'
      path: '/supplies-admin'
      fullPath: '/supplies-admin'
      preLoaderRoute: typeof ProtectedSuppliesAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/storage': {
      id: '/_protected/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof ProtectedStorageRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/qc-summary': {
      id: '/_protected/qc-summary'
      path: '/qc-summary'
      fullPath: '/qc-summary'
      preLoaderRoute: typeof ProtectedQcSummaryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/qc-reports': {
      id: '/_protected/qc-reports'
      path: '/qc-reports'
      fullPath: '/qc-reports'
      preLoaderRoute: typeof ProtectedQcReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/production-standards': {
      id: '/_protected/production-standards'
      path: '/production-standards'
      fullPath: '/production-standards'
      preLoaderRoute: typeof ProtectedProductionStandardsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/production-setup': {
      id: '/_protected/production-setup'
      path: '/production-setup'
      fullPath: '/production-setup'
      preLoaderRoute: typeof ProtectedProductionSetupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/production-excel': {
      id: '/_protected/production-excel'
      path: '/production-excel'
      fullPath: '/production-excel'
      preLoaderRoute: typeof ProtectedProductionExcelRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/production-dashboard': {
      id: '/_protected/production-dashboard'
      path: '/production-dashboard'
      fullPath: '/production-dashboard'
      preLoaderRoute: typeof ProtectedProductionDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/packing-summary': {
      id: '/_protected/packing-summary'
      path: '/packing-summary'
      fullPath: '/packing-summary'
      preLoaderRoute: typeof ProtectedPackingSummaryRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/packing-reports': {
      id: '/_protected/packing-reports'
      path: '/packing-reports'
      fullPath: '/packing-reports'
      preLoaderRoute: typeof ProtectedPackingReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/manage-policies': {
      id: '/_protected/manage-policies'
      path: '/manage-policies'
      fullPath: '/manage-policies'
      preLoaderRoute: typeof ProtectedManagePoliciesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/manage': {
      id: '/_protected/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ProtectedManageRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/maintenance-master': {
      id: '/_protected/maintenance-master'
      path: '/maintenance-master'
      fullPath: '/maintenance-master'
      preLoaderRoute: typeof ProtectedMaintenanceMasterRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/maintenance-admin': {
      id: '/_protected/maintenance-admin'
      path: '/maintenance-admin'
      fullPath: '/maintenance-admin'
      preLoaderRoute: typeof ProtectedMaintenanceAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logs-update': {
      id: '/_protected/logs-update'
      path: '/logs-update'
      fullPath: '/logs-update'
      preLoaderRoute: typeof ProtectedLogsUpdateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logs': {
      id: '/_protected/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof ProtectedLogsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/job-lookup': {
      id: '/_protected/job-lookup'
      path: '/job-lookup'
      fullPath: '/job-lookup'
      preLoaderRoute: typeof ProtectedJobLookupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expenses-reports': {
      id: '/_protected/expenses-reports'
      path: '/expenses-reports'
      fullPath: '/expenses-reports'
      preLoaderRoute: typeof ProtectedExpensesReportsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expenses-dashboard': {
      id: '/_protected/expenses-dashboard'
      path: '/expenses-dashboard'
      fullPath: '/expenses-dashboard'
      preLoaderRoute: typeof ProtectedExpensesDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/control': {
      id: '/_protected/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ProtectedControlRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin-policy': {
      id: '/_protected/admin-policy'
      path: '/admin-policy'
      fullPath: '/admin-policy'
      preLoaderRoute: typeof ProtectedAdminPolicyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/employee-profile/$id': {
      id: '/_protected/employee-profile/$id'
      path: '/employee-profile/$id'
      fullPath: '/employee-profile/$id'
      preLoaderRoute: typeof ProtectedEmployeeProfileIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/public/hooks/line-daily-send': {
      id: '/api/public/hooks/line-daily-send'
      path: '/api/public/hooks/line-daily-send'
      fullPath: '/api/public/hooks/line-daily-send'
      preLoaderRoute: typeof ApiPublicHooksLineDailySendRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminPolicyRoute: typeof ProtectedAdminPolicyRoute
  ProtectedControlRoute: typeof ProtectedControlRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedExpensesDashboardRoute: typeof ProtectedExpensesDashboardRoute
  ProtectedExpensesReportsRoute: typeof ProtectedExpensesReportsRoute
  ProtectedJobLookupRoute: typeof ProtectedJobLookupRoute
  ProtectedLogsRoute: typeof ProtectedLogsRoute
  ProtectedLogsUpdateRoute: typeof ProtectedLogsUpdateRoute
  ProtectedMaintenanceAdminRoute: typeof ProtectedMaintenanceAdminRoute
  ProtectedMaintenanceMasterRoute: typeof ProtectedMaintenanceMasterRoute
  ProtectedManageRoute: typeof ProtectedManageRoute
  ProtectedManagePoliciesRoute: typeof ProtectedManagePoliciesRoute
  ProtectedPackingReportsRoute: typeof ProtectedPackingReportsRoute
  ProtectedPackingSummaryRoute: typeof ProtectedPackingSummaryRoute
  ProtectedProductionDashboardRoute: typeof ProtectedProductionDashboardRoute
  ProtectedProductionExcelRoute: typeof ProtectedProductionExcelRoute
  ProtectedProductionSetupRoute: typeof ProtectedProductionSetupRoute
  ProtectedProductionStandardsRoute: typeof ProtectedProductionStandardsRoute
  ProtectedQcReportsRoute: typeof ProtectedQcReportsRoute
  ProtectedQcSummaryRoute: typeof ProtectedQcSummaryRoute
  ProtectedStorageRoute: typeof ProtectedStorageRoute
  ProtectedSuppliesAdminRoute: typeof ProtectedSuppliesAdminRoute
  ProtectedSuppliesDashboardRoute: typeof ProtectedSuppliesDashboardRoute
  ProtectedSuppliesReportsRoute: typeof ProtectedSuppliesReportsRoute
  ProtectedEmployeeProfileIdRoute: typeof ProtectedEmployeeProfileIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminPolicyRoute: ProtectedAdminPolicyRoute,
  ProtectedControlRoute: ProtectedControlRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedExpensesDashboardRoute: ProtectedExpensesDashboardRoute,
  ProtectedExpensesReportsRoute: ProtectedExpensesReportsRoute,
  ProtectedJobLookupRoute: ProtectedJobLookupRoute,
  ProtectedLogsRoute: ProtectedLogsRoute,
  ProtectedLogsUpdateRoute: ProtectedLogsUpdateRoute,
  ProtectedMaintenanceAdminRoute: ProtectedMaintenanceAdminRoute,
  ProtectedMaintenanceMasterRoute: ProtectedMaintenanceMasterRoute,
  ProtectedManageRoute: ProtectedManageRoute,
  ProtectedManagePoliciesRoute: ProtectedManagePoliciesRoute,
  ProtectedPackingReportsRoute: ProtectedPackingReportsRoute,
  ProtectedPackingSummaryRoute: ProtectedPackingSummaryRoute,
  ProtectedProductionDashboardRoute: ProtectedProductionDashboardRoute,
  ProtectedProductionExcelRoute: ProtectedProductionExcelRoute,
  ProtectedProductionSetupRoute: ProtectedProductionSetupRoute,
  ProtectedProductionStandardsRoute: ProtectedProductionStandardsRoute,
  ProtectedQcReportsRoute: ProtectedQcReportsRoute,
  ProtectedQcSummaryRoute: ProtectedQcSummaryRoute,
  ProtectedStorageRoute: ProtectedStorageRoute,
  ProtectedSuppliesAdminRoute: ProtectedSuppliesAdminRoute,
  ProtectedSuppliesDashboardRoute: ProtectedSuppliesDashboardRoute,
  ProtectedSuppliesReportsRoute: ProtectedSuppliesReportsRoute,
  ProtectedEmployeeProfileIdRoute: ProtectedEmployeeProfileIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  AdminRoute: AdminRoute,
  ExpenseMineRoute: ExpenseMineRoute,
  ExpenseScanRoute: ExpenseScanRoute,
  MaintenanceRoute: MaintenanceRoute,
  PackingRoute: PackingRoute,
  QcRoute: QcRoute,
  ScanRoute: ScanRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuppliesRoute: SuppliesRoute,
  SuppliesRequestRoute: SuppliesRequestRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksLineDailySendRoute: ApiPublicHooksLineDailySendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
